backend:
  name: git-gateway
  branch: main 
media_folder: "public/assets/blog"
public_folder: "assets/blog"
publish_mode: editorial_workflow
drafts_enabled: true
site_url: https://thisjedicodes.netlify.app/
display_url: https://thisjedicodes.netlify.app/
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # URL of post
    preview_path: "blog/{{slug}}" # Preview URL of the post
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["post"]
        allow_add: true
        field:
          label: "Tag"
          name: "tag"
          widget: "select"
          options: 
            - post
            - featured
            - javascript
            - c#
            - css
            - html
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }